exp_name: 'baseline_mcs'
outdir: './experiments/'

num_gpu: 1

dataset:
    train_prefix: '.../Product10K/train/'
    train_list: '.../Product10K/train.csv'
    val_prefix: '.../Product10K/test/'
    val_list: '.../Product10K/test_kaggletest.csv'
    seed: 42
    num_of_classes: 9691
    input_size: 224
    batch_size: 256
    augmentations: 'default'
    augmentations_valid: 'default'
    num_workers: 24

model:
    arch: 'resnet18'

train:
    optimizer: 'SGD'
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    lr_schedule:
        name: 'StepLR'
        step_size: 30
        gamma: 0.1
    n_epoch: 50
    label_smoothing: false
    eps: 0.01
    freq_vis: 500